// <auto-generated />
using KutuphaneMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneMVC.Migrations
{
    [DbContext(typeof(KutuphaneContext))]
    [Migration("20250501200314_a1")]
    partial class a1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("KutuphaneMVC.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("AEposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ASifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("ATelefon")
                        .HasColumnType("TEXT");

                    b.HasKey("AdminId");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("KutuphaneMVC.Models.EmanetKitap", b =>
                {
                    b.Property<int>("EKitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EKitapAdi")
                        .HasColumnType("TEXT");

                    b.Property<int>("EKitapAdiSayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EKullaniciAD")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETur")
                        .HasColumnType("TEXT");

                    b.Property<string>("EYazar")
                        .HasColumnType("TEXT");

                    b.HasKey("EKitapId");

                    b.ToTable("emanetKitaps");
                });

            modelBuilder.Entity("KutuphaneMVC.Models.Kitap", b =>
                {
                    b.Property<int>("KitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapAdi")
                        .HasColumnType("TEXT");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tur")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yazar")
                        .HasColumnType("TEXT");

                    b.HasKey("KitapId");

                    b.ToTable("kitaps");
                });

            modelBuilder.Entity("KutuphaneMVC.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("KEposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("KSifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("KTelefon")
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciId");

                    b.ToTable("EntityNames");
                });

            modelBuilder.Entity("KutuphaneMVC.Models.Mesaj", b =>
                {
                    b.Property<int>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MKAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MMesaj")
                        .HasColumnType("TEXT");

                    b.HasKey("MId");

                    b.ToTable("mesajs");
                });
#pragma warning restore 612, 618
        }
    }
}
