// <auto-generated />
using System;
using KutuphaneMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneMVC.Migrations
{
    [DbContext(typeof(KutuphaneContext))]
    [Migration("20250423192057_a1")]
    partial class a1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("KutuphaneMVC.Models.Admin", b =>
                {
                    b.Property<int>("AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("AEposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("AKapakFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("ASifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("ATelefon")
                        .HasColumnType("TEXT");

                    b.HasKey("AId");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("KutuphaneMVC.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KapakFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapTuruİd")
                        .HasColumnType("TEXT");

                    b.Property<string>("SayfaSayisi")
                        .HasColumnType("TEXT");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YayinEvi")
                        .HasColumnType("TEXT");

                    b.Property<string>("YazarAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("kitaps");
                });

            modelBuilder.Entity("KutuphaneMVC.Models.KullaniciClass", b =>
                {
                    b.Property<int>("KId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KEposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("KKapakFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("KSifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("KTelefon")
                        .HasColumnType("TEXT");

                    b.HasKey("KId");

                    b.ToTable("kullaniciClasses");
                });

            modelBuilder.Entity("KutuphaneMVC.Models.Yonetici", b =>
                {
                    b.Property<int>("YId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("YAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("YEposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("YKapakFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("YSifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("YTelefon")
                        .HasColumnType("TEXT");

                    b.HasKey("YId");

                    b.ToTable("yoneticis");
                });
#pragma warning restore 612, 618
        }
    }
}
